import hashlib
import httpx
from pydantic import BaseModel
from typing import List, Dict, Any, Optional

HIBP_API_URL = "https://api.pwnedpasswords.com/range/"

class PasswordCheckResult(BaseModel):
    is_pwned: bool
    breach_count: int
    sha1_prefix: str
    message: str
    disclaimer: str
    recommendations: List[str]

async def check_password_pwned(password: str, timeout_seconds: float = 3.0) -> PasswordCheckResult:
    """
    Checks if a password has been compromised using HIBP Pwned Passwords with K-Anonymity.
    CRITICAL: Plaintext password is NEVER logged, stored, or transmitted outside local memory.
    Only the first 5 characters of the SHA-1 hash are sent to HIBP API.
    """
    if not password:
        return PasswordCheckResult(
            is_pwned=False,
            breach_count=0,
            sha1_prefix="",
            message="Empty password provided.",
            disclaimer="No match found in checked dataset does NOT guarantee a password is safe.",
            recommendations=["Choose a strong, unique passphrase with at least 14 characters."]
        )

    # 1. Compute SHA-1 hash locally in memory
    sha1_hash = hashlib.sha1(password.encode("utf-8")).hexdigest().upper()
    prefix = sha1_hash[:5]
    suffix = sha1_hash[5:]

    disclaimer = "A 'No Match' result means this password was not found in public breach datasets. It does NOT guarantee the password is safe or uncompromised."

    try:
        async with httpx.AsyncClient(timeout=timeout_seconds, trust_env=False) as client:
            response = await client.get(f"{HIBP_API_URL}{prefix}", headers={"User-Agent": "ApatiAspis-SecurityChecker/1.0"})

            if response.status_code != 200:
                return PasswordCheckResult(
                    is_pwned=False,
                    breach_count=0,
                    sha1_prefix=prefix,
                    message="HIBP Pwned Passwords service currently unavailable.",
                    disclaimer=disclaimer,
                    recommendations=["Use a password manager to generate unique, complex passwords."]
                )

            # 2. Parse response lines (SUFFIX:COUNT)
            response_text = response.text
            match_count = 0
            is_pwned = False

            for line in response_text.splitlines():
                line = line.strip()
                if not line or ":" not in line:
                    continue
                h_suffix, count_str = line.split(":", 1)
                if h_suffix.upper() == suffix:
                    match_count = int(count_str)
                    is_pwned = True
                    break

            if is_pwned:
                message = f"WARNING: This password has appeared in public data breaches {match_count:,} times!"
                recommendations = [
                    "Change this password immediately wherever it is used.",
                    "Do NOT use this password for any account.",
                    "Use a password manager to generate a unique random password."
                ]
            else:
                message = "No match found in public data breach datasets."
                recommendations = [
                    "Ensure this password is at least 14-16 characters long.",
                    "Do not reuse this password across multiple accounts.",
                    "Enable Multi-Factor Authentication (MFA) on accounts using this password."
                ]

            return PasswordCheckResult(
                is_pwned=is_pwned,
                breach_count=match_count,
                sha1_prefix=prefix,
                message=message,
                disclaimer=disclaimer,
                recommendations=recommendations
            )

    except (httpx.TimeoutException, httpx.RequestError, Exception):
        return PasswordCheckResult(
            is_pwned=False,
            breach_count=0,
            sha1_prefix=prefix,
            message="Password breach lookup timed out or service unavailable.",
            disclaimer=disclaimer,
            recommendations=["Always use unique, complex passwords generated by a password manager."]
        )
