"""create_scan_and_checkup_tables

Revision ID: bc9cd799e486
Revises: 
Create Date: 2026-08-08 16:25:20.685978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9cd799e486'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkup_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('security_level', sa.String(length=20), nullable=False),
    sa.Column('weakest_category', sa.String(length=100), nullable=False),
    sa.Column('recommendations_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkup_records_id'), 'checkup_records', ['id'], unique=False)
    op.create_table('scan_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('indicator', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('reasons_json', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_records_domain'), 'scan_records', ['domain'], unique=False)
    op.create_index(op.f('ix_scan_records_id'), 'scan_records', ['id'], unique=False)
    op.create_index(op.f('ix_scan_records_scan_type'), 'scan_records', ['scan_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_records_scan_type'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_id'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_domain'), table_name='scan_records')
    op.drop_table('scan_records')
    op.drop_index(op.f('ix_checkup_records_id'), table_name='checkup_records')
    op.drop_table('checkup_records')
    # ### end Alembic commands ###
